### ISSUE TITLE
antrea jobs have completely stopped working

### ISSUE THREAD

**Issue by mattfenwick** [K8sbykeshed/cyclonus-artifacts#3]
Check out the latest antrea jobs: https://github.com/K8sbykeshed/cyclonus-artifacts/actions/runs/716882009

 - all requests are allowed, regardless of network policy: policies are no longer being enforced

I'm not sure what exactly is happening in the github actions -- we may need more logging around pod status there.

When I run locally, all of the antrea-agent pods have an antrea-agent container which doesn't work:

<img width="1394" alt="Screen Shot 2021-04-05 at 8 47 26 AM" src="https://user-images.githubusercontent.com/952655/113575286-a13e4d00-95eb-11eb-9369-2a3eebb3c366.png">

with this in the logs:

```
 W0405 12:49:55.979017       1 networkpolicy_controller.go:589] Failed to start watch for NetworkPolicy: unknown (get networkpolicies.controlplane.antrea.io)
```

Container statuses:

```
  containerStatuses:
  - containerID: containerd://504ec18c94fab7c393e3ff0f5fce2b45ed4a77e2467d005f8ed9e633a7e1a729
    image: projects.registry.vmware.com/antrea/antrea-ubuntu:latest
    imageID: projects.registry.vmware.com/antrea/antrea-ubuntu@sha256:50b48d70c983b53bd75023002e712310061977922dab8c4602f2d3c4bf9c2858
    lastState: {}
    name: antrea-agent
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-04-05T12:31:44Z"
  - containerID: containerd://9422ea08073b901107871fb307d86c38a2eebb33d4faf9777c2118c2f09c22b9
    image: projects.registry.vmware.com/antrea/antrea-ubuntu:latest
    imageID: projects.registry.vmware.com/antrea/antrea-ubuntu@sha256:50b48d70c983b53bd75023002e712310061977922dab8c4602f2d3c4bf9c2858
    lastState: {}
    name: antrea-ovs
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-04-05T12:31:44Z"
```

## Possible cause: change in projects.registry.vmware.com/antrea/antrea-ubuntu:latest image?

As seen above, the images are `projects.registry.vmware.com/antrea/antrea-ubuntu:latest` which was last updated two days ago:

```
$ docker inspect projects.registry.vmware.com/antrea/antrea-ubuntu:latest
[
    {
        "Id": "sha256:315b1fecf823aea3620542f627d079febbb58f0b58b8fca37c4a26a602de2a18",
        "RepoTags": [
            "projects.registry.vmware.com/antrea/antrea-ubuntu:latest"
        ],
        "RepoDigests": [
            "projects.registry.vmware.com/antrea/antrea-ubuntu@sha256:74987404541ada1ba9a0356c9feaf779fd7922111f016e8a41eb171107b7a92e"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-04-03T03:16:38.29653179Z",
```
